force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Incomplete</fullName>
            </value>
            <value>
                <fullName>Succesful</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TransactionController.cls
/**
 * @description       : 
 * @author            : horobei
 * @group             : 
 * @last modified on  : 08-08-2022
 * @last modified by  : horobei
**/
public without sharing class TransactionController {
    private static final String STATUS = 'Succeeded';
    /**
    * @description 
    * @author horobei | 08-04-2022 
    * @param recordId 
    * @return TransactionWrapper 
    **/
    @AuraEnabled
    public static TransactionWrapper getTransaction(String recordId){
        try{
            String fieldName = setReletedObject(recordId);
            if (String.isBlank(fieldName)) {
                return null;
            }
            String  query = 'Select Id, Receipt__c, Status__c From Transaction__c Where Status__c = :STATUS And '
                +String.escapeSingleQuotes(fieldName)+' =:recordId Order by CreatedDate DESC limit 1';
        // if (Schema.sObjectType.Transaction__c.fields.Receipt__c.isAccessible() && 
        //     Schema.sObjectType.Transaction__c.fields.Status__c.isAccessible() && 
        //     Schema.sObjectType.Transaction__c.fields.Case__c.isAccessible() && 
        //     Schema.sObjectType.Transaction__c.fields.Opportunity__c.isAccessible() && 
        //     Schema.sObjectType.Transaction__c.fields.Order__c.isAccessible()) {
            Transaction__c t = Database.query(query);
                return new TransactionWrapper(t);
        // }
            // return null;
        }catch(System.QueryException e){
            return null;
        }
    }

    /**
    * @description 
    * @author horobei | 08-04-2022 
    * @param recordId 
    * @return String 
    **/
    private static String setReletedObject(String recordId){
        String objApiName = Id.valueOf(recordId).getSObjectType().getDescribe().getName();  
        switch on objApiName {
            when 'Case' {
                return 'Case__c';
            }
            when 'Opportunity' {
                return 'Opportunity__c';
            }
            when 'Order' {
                return 'Order__c';
            }
        }
        return null;
    }

    /** @description TransactionWrapper **/
    public class TransactionWrapper {
        /** @description id **/
        @AuraEnabled
        public String id {get;set;}
        @AuraEnabled
        /** @description receipt **/
        public String receipt {get;set;}
        @AuraEnabled
        /** @description status **/
        public String status {get;set;}

        /**
        * @description 
        * @author horobei | 08-04-2022 
        * @param tr 
        **/
        public TransactionWrapper(Transaction__c tr){
            this.id = tr.Id;
            this.receipt = tr.Receipt__c;
            this.status = tr.Status__c;
        }
    }
}